#!/bin/bash

upload() {
    api_url="https://sm.ms/api/upload"
    info=$(curl -sF "smfile=@$1" $api_url)
    code=$(echo $info | jq -r .code)
    if [ $code = "success" ]; then
        name=$(echo $info | jq -r .data.filename)
        img_url=$(echo $info | jq -r .data.url)
        echo $img_url | xclip -selection clipboard
        notify-send "$name uploaded and url copied"
    else
        notify-send -u critical "UPLOAD FAILED"
    fi
}

upload_termux() {
    api_url="https://sm.ms/api/upload"
    info=$(curl -sF "smfile=@$1" $api_url)
    code=$(echo $info | jq -r .code)
    if [ $code = "success" ]; then
        name=$(echo $info | jq -r .data.filename)
        img_url=$(echo $info | jq -r .data.url)
        termux-clipboard-set $img_url
        echo "$name uploaded and url copied"
    else
        echo "UPLOAD FAILED"
    fi
}

upload $1
# upload_termux $1
