#!/usr/bin/env bash

dir=""

files=()
j=0

get_files() {
    for i in $(ls $dir -1); do
       files[$j]=$i
       j=$(expr $j + 1)
    done
}

# have no idea why this doesn't work in termux
# get_rand(){
#     min=$1
#     max=$(($2-$min+1))
#     num=$(date +%s%N)
#     rand_int=$(($num%$max+$min))
#     return $rand_int
# }

set_wallpaper() {
    get_files
    max=${#files[@]}
    num=$(python -c "import random;print(random.randint(1, $max))")
    file=${files[$num]}
    path="$dir/$file"
    termux-wallpaper -f $path
}

set_wallpaper
