#!/usr/bin/env bash

dir="$HOME/Pictures/Screenshots"

files=()
j=0

get_files() {
    for i in $(ls $dir -1); do
       files[$j]=$i
       j=$(expr $j + 1)
    done
}

get_rand(){
    min=$1
    max=$(($2-$min+1))
    num=$(date +%s%N)
    rand_int=$(($num%$max+$min))
    return $rand_int
}


set_wallpaper() {
    get_files
    max=${#files[@]}
    get_rand 1 $max
    file=${files[$?]}
    path="$dir/$file"
    termux-wallpaper -f $path
}

set_wallpaper
